version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - ssh:/app/ssh/:rw
      - ./public/:/app/public/:rw
      - ./app/:/usr/local/openresty/site/lualib/:rw
      - ./docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:rw
    links:
      - redis
  ssh:
    image: maltyxx/sshd
    command: "user::1000"
    ports:
      - "2222:22"
    volumes:
      - ssh:/home/user/.ssh/:ro
      - ./docker/sshd/sshd_config:/usr/local/etc/sshd/sshd_config:ro
  redis:
    image: redis
    volumes:
      - ./bin:/app/bin

volumes:
  ssh:
    external: false
